package zk

import "github.com/stretchr/testify/mock"

// mockConnectorInterface is an autogenerated mock type for the ConnectorInterface type
type mockConnectorInterface struct {
	mock.Mock
}

// Connect provides a mock function with given fields: path
func (_m *mockConnectorInterface) Connect(path string) (Connection, error) {
	ret := _m.Called(path)

	var r0 Connection
	if rf, ok := ret.Get(0).(func(string) Connection); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Connection)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
