package mocks

import (
	"github.com/klarna/eremetic"
	"github.com/stretchr/testify/mock"
)

// ZkConnectorInterface is an autogenerated mock type for the ZkConnectorInterface type
type ZkConnectorInterface struct {
	mock.Mock
}

// Connect provides a mock function with given fields: path
func (_m *ZkConnectorInterface) Connect(path string) (eremetic.ZkConnection, error) {
	ret := _m.Called(path)

	var r0 eremetic.ZkConnection
	if rf, ok := ret.Get(0).(func(string) eremetic.ZkConnection); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(eremetic.ZkConnection)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
