package boltdb

import (
	"github.com/boltdb/bolt"
	"github.com/stretchr/testify/mock"
)

// mockConnection is an autogenerated mock type for the Connection type
type mockConnection struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *mockConnection) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: _a0
func (_m *mockConnection) Update(_a0 func(*bolt.Tx) error) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(func(*bolt.Tx) error) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// View provides a mock function with given fields: _a0
func (_m *mockConnection) View(_a0 func(*bolt.Tx) error) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(func(*bolt.Tx) error) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
